name: Mark Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs within 7 days.
            Thank you for your contributions.
          close-issue-message: |
            This issue was automatically closed due to inactivity. If you believe this
            was done in error, please reopen the issue or create a new one.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs within 7 days.
            Please update or rebase your PR to keep it active.
          close-pr-message: |
            This pull request was automatically closed due to inactivity. If you'd like to
            continue working on this, please reopen the PR or create a new one.
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: 'pinned,security,good first issue'
          exempt-pr-labels: 'pinned,security,work in progress'
          operations-per-run: 30

